services:

  mysql:

    image: mysql:8

    container_name: iron-dome-db

    restart: always

    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iron_dome

    volumes:
      - mysql-data1:/var/lib/mysql
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql

volumes:
  mysql-data1:
  